name: rnamsm
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pytorch-lightning=1.5.*
  - torchaudio=0.7.2
  - numpy=1.19.*
  - scipy=1.6.*
  - pandas=1.3.*
  - scikit-learn=0.24.*
  - matplotlib=3.3.*
  - seaborn=0.11.*
  - biopython=1.78
  - jupyter
  - ipykernel
  - pip
  - pip:
    - transformers==4.17.0
    - torchmetrics==0.7.3
    - tensorboard==2.8.0
    - tensorboardx==2.5
    - fair-esm==1.0.2
    - rna-fm==0.1.0
    - einops==0.6.0
    - opencv-python==4.7.0.68
    - tqdm==4.62.0
    - ml-collections==0.1.1
    - tokenizers==0.12.1
    - sacremoses==0.0.49
    - pandas-datareader==0.10.0
